#!/usr/bin/env bash

set -eu

override=$(git config guessDefaultBranch.override || true)

if [[ -n "$override" ]]; then
    echo "$override"
    exit
fi

well_known=$(git config guessDefaultBranch.wellKnown || true)
well_known=${well_known:-master main develop trunk}

candidates=($(git branch --format='%(refname:short)' --list $well_known))

for branch in $well_known; do
    if [[ " ${candidates[@]} " = *" $branch "* ]]; then
        echo "$branch"
        exit
    fi
done

fallback=$(git config guessDefaultBranch.fallback || true)
fallback=${fallback:-$(git config init.defaultBranch || true)}
fallback=${fallback:-master}

echo "$fallback"
